import { DesignPreset, Project, PromptTemplate } from './types';

export const DESIGN_PRESETS: DesignPreset[] = [
  {
    id: 'ui-wireframe',
    name: 'UI/UX Wireframe',
    description: 'Clean, high-fidelity black-and-white structural blueprints.',
    icon: 'LayoutGrid',
    samplePrompt: 'Convert this sketchy UI to a high-fidelity web app wireframe, using modular cards, precise alignment, clear typography, and input fields.',
    bgColor: 'from-blue-600/20 to-indigo-600/20',
    accentColor: '#3B82F6',
  },
  {
    id: 'mobile-app',
    name: 'Mobile App Design',
    description: 'Beautiful iOS or Android mobile application screens.',
    icon: 'Smartphone',
    samplePrompt: 'Transform this hand-drawn mobile app layout into a sleek modern fitness tracker iOS screen with a dark elegant interface, glassmorphism telemetry trackers, and neon gradient details.',
    bgColor: 'from-pink-600/20 to-purple-600/20',
    accentColor: '#EC4899',
  },
  {
    id: 'dashboard',
    name: 'Dashboard Design',
    description: 'Feature-heavy web panels with charts & metrics.',
    icon: 'LineChart',
    samplePrompt: 'Redesign this grid sketch into a premium SaaS analytics dashboard, containing glowing charts, telemetry meters, sidebars, active project rows, and modern blue-to-teal glow aesthetics.',
    bgColor: 'from-cyan-600/20 to-blue-600/20',
    accentColor: '#06B6D4',
  },
  {
    id: 'landing-page',
    name: 'Website Landing Page',
    description: 'Futuristic marketing pages with high-conversion layouts.',
    icon: 'Compass',
    samplePrompt: 'Render this landing page wireframe into a beautiful Web3 AI startup landing page with immersive high-end illustration banners, clean gradients, glowing buttons, and smooth responsive sections.',
    bgColor: 'from-violet-600/20 to-fuchsia-600/20',
    accentColor: '#8B5CF6',
  },
  {
    id: 'illustration',
    name: 'Illustration Art',
    description: 'Polished vector or high-end artistic digital art.',
    icon: 'Palette',
    samplePrompt: 'Turn this simple sketch of a landscape into a beautiful modern vector digital illustration, with minimalist warm earth tones, soft shadows, and organic sun elements.',
    bgColor: 'from-amber-600/20 to-orange-600/20',
    accentColor: '#F59E0B',
  },
  {
    id: 'logo-design',
    name: 'Logo Design',
    description: 'Minimalist, memorable vector corporate emblems.',
    icon: 'Fingerprint',
    samplePrompt: 'Convert this rough scribble into a clean, minimalist, high-end tech corporate logo, centered vector icon, flat professional layout, dark mode contrast.',
    bgColor: 'from-emerald-600/20 to-teal-600/20',
    accentColor: '#10B981',
  },
  {
    id: 'architecture',
    name: 'Architecture Sketch',
    description: 'Stunning conceptual real estate blueprints.',
    icon: 'Home',
    samplePrompt: 'Transform this hand-drawn building facade into an elegant, modernist glass villa mockup, with photorealistic lighting, surrounding pine forest, clear reflections, and concrete accents.',
    bgColor: 'from-stone-600/20 to-neutral-600/20',
    accentColor: '#78716C',
  },
  {
    id: 'interior',
    name: 'Interior Design',
    description: 'Beautifully furnished and styled living spaces.',
    icon: 'Armchair',
    samplePrompt: 'Render this living room sketch into a premium interior design, Scandinavian minimalist style, cozy lighting, wooden textures, warm fireplace, green plants, and soft textiles.',
    bgColor: 'from-yellow-600/20 to-amber-500/20',
    accentColor: '#EAB308',
  },
  {
    id: 'product-prototype',
    name: 'Product Prototype',
    description: 'Industrial tech product physical designs.',
    icon: 'Cpu',
    samplePrompt: 'Convert this rough sketch of a pair of headphones into a professional 3D industrial product design, matte black finish with brushed copper accents, studio lighting, highly detailed chassis.',
    bgColor: 'from-indigo-600/20 to-cyan-600/20',
    accentColor: '#6366F1',
  },
  {
    id: 'anime',
    name: 'Anime Style',
    description: 'Vibrant Japanese animation stylized drawings.',
    icon: 'Sparkles',
    samplePrompt: 'Transform this simple character sketch into a beautiful detailed high-end anime character design, cyberpunk aesthetic, vivid neon lights, cinematic key illumination, dramatic background.',
    bgColor: 'from-rose-600/20 to-red-600/20',
    accentColor: '#F43F5E',
  },
  {
    id: 'minimal-modern',
    name: 'Minimal Modern Style',
    description: 'Sleek, high-end Swiss and editorial designs.',
    icon: 'Maximize',
    samplePrompt: 'Render this rough draft as a minimalist Swiss layout, featuring bold Helvetica typography, oversized column grid layouts, high contrast, immense breathing room, and absolute clarity.',
    bgColor: 'from-slate-600/20 to-zinc-600/20',
    accentColor: '#64748B',
  },
  {
    id: 'corporate-professional',
    name: 'Corporate Professional',
    description: 'Highly polished executive corporate designs.',
    icon: 'Briefcase',
    samplePrompt: 'Convert this wireframe structure into a premium enterprise software interface with rich clean grids, professional deep navy color palettes, verified badges, and solid structural integrity.',
    bgColor: 'from-blue-700/20 to-slate-700/20',
    accentColor: '#1D4ED8',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    title: 'Cloud Analytics Main Dashboard',
    createdAt: '2026-05-07 14:22',
    style: 'dashboard',
    isFavorite: true,
    prompt: 'Convert this grid sketch into a premium SaaS analytics dashboard, containing glowing charts, telemetry meters, sidebars, active project rows, and modern blue-to-teal glow aesthetics.',
    aiCreditsUsed: 15,
    sketchImage: 'https://images.unsplash.com/photo-1541462608143-67571c6738dd?auto=format&fit=crop&w=600&q=80',
    designedImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    notes: 'Primary layout for the corporate investor deck. Shape detection successfully snapped modular columns.',
    layoutAnalysis: {
      components: [
        { id: 'c1', type: 'Header Navigation Panel', confidence: 0.96, boundingBox: { x: 5, y: 5, w: 90, h: 8 }, suggestion: 'Add a search bar and workspace avatar in the top right element.' },
        { id: 'c2', type: 'Sidebar Menu Items', confidence: 0.92, boundingBox: { x: 5, y: 15, w: 15, h: 70 }, suggestion: 'Include a collapsed state for narrower screen resolutions.' },
        { id: 'c3', type: 'Comparison Chart Container', confidence: 0.95, boundingBox: { x: 23, y: 18, w: 50, h: 32 }, suggestion: 'Renders excellently as a multi-line Recharts dynamic component.' },
        { id: 'c4', type: 'Stats Row widgets', confidence: 0.88, boundingBox: { x: 23, y: 53, w: 72, h: 12 }, suggestion: 'Add minor upwards arrow icons for positive business trends.' },
      ],
      colors: ['#0F172A', '#06B6D4', '#2563EB', '#10B981'],
      typography: 'Inter, system-ui, sans-serif',
      score: 94,
      feedback: [
        'Excellent high-fidelity layout representation.',
        'Spacings represent precise grid grids fitting 12-column layouts.',
        'Contrast levels are optimized for Dark Mode displays.',
      ],
    },
  },
  {
    id: 'proj-2',
    title: 'E-Commerce Hero Landing',
    createdAt: '2026-05-06 18:05',
    style: 'landing-page',
    isFavorite: false,
    prompt: 'Render this landing page wireframe into a beautiful Web3 AI startup landing page with immersive high-end illustration banners, clean gradients, glowing buttons, and smooth responsive sections.',
    aiCreditsUsed: 12,
    sketchImage: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?auto=format&fit=crop&w=600&q=80',
    designedImage: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
    notes: 'Converted the visual banner to high-resolution organic design with smooth text wrapping.',
    layoutAnalysis: {
      components: [
        { id: 'c5', type: 'Hero Main Headline', confidence: 0.98, boundingBox: { x: 10, y: 20, w: 45, h: 25 }, suggestion: 'Use a bold serif font (e.g. Playfair Display) to highlight premium branding.' },
        { id: 'c6', type: 'Call to Action Button', confidence: 0.94, boundingBox: { x: 10, y: 48, w: 15, h: 6 }, suggestion: 'Apply a solid backdrop shadow with gradient transition.' },
        { id: 'c7', type: 'Featured Image Banner', confidence: 0.91, boundingBox: { x: 60, y: 15, w: 35, h: 50 }, suggestion: 'Incorporate 3D abstract rendering for maximum futuristic appeal.' },
      ],
      colors: ['#0F172A', '#8B5CF6', '#F59E0B', '#F3F4F6'],
      typography: 'Inter, Playfair Display, serif',
      score: 89,
      feedback: [
        'Hero composition conforms perfectly to golden ratio rules.',
        'High readability index due to substantial margin distribution.',
      ],
    },
  },
  {
    id: 'proj-3',
    title: 'Modern Coffee Cup Logo',
    createdAt: '2026-05-05 09:12',
    style: 'logo-design',
    isFavorite: true,
    prompt: 'Convert this rough scribble into a clean, minimalist, high-end tech corporate logo, centered vector icon, flat professional layout, dark mode contrast.',
    aiCreditsUsed: 10,
    sketchImage: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=600&q=80',
    designedImage: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=1200&q=80',
    notes: 'Minimalist brand identity design. Extracted contours flawlessly from drawing canvas.',
  },
  {
    id: 'proj-4',
    title: 'Coastal Minimalist Villa Concept',
    createdAt: '2026-05-04 11:30',
    style: 'architecture',
    isFavorite: false,
    prompt: 'Transform this hand-drawn building facade into an elegant, modernist glass villa mockup, with photorealistic lighting, surrounding pine forest, clear reflections, and concrete accents.',
    aiCreditsUsed: 15,
    sketchImage: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=600&q=80',
    designedImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    notes: 'High-end structural rendering. Outstanding light-depth analysis in the pine forests.',
  },
];

export const PROMPT_TEMPLATES: PromptTemplate[] = [
  {
    category: 'SaaS & UI/UX',
    title: 'Glassmorphism Finance App',
    prompt: 'High fidelity iOS finance screen with blue translucent glass cards, neon teal graphs, and white Helvetica typography.',
  },
  {
    category: 'SaaS & UI/UX',
    title: 'Minimalist Cyberpunk eCommerce',
    prompt: 'A bold, brutalist grid-based layout for an e-commerce platform with oversized neon green elements, solid 1px black borders, and active product grids.',
  },
  {
    category: 'Art & Logo',
    title: 'Corporate Monogram Emblem',
    prompt: 'Extremely clean vector minimalist technology company monogram, matte gold gradient over luxury deep gray background.',
  },
  {
    category: 'Industrial & Product',
    title: 'Futuristic Smartwatch Render',
    prompt: 'Professional industrial 3D product design of a futuristic smartwatch, curved glass display with detailed mechanical rotating crown.',
  },
];
